name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Push to Gitee
      uses: nick-invision/retry@v2
      with:
        max_attempts: 3
        timeout_minutes: 5
        command: |
          git config --global user.name "七星瓢虫"
          git config --global user.email "49963270@qq.com"
          git remote add gitee https://49963270:${{ secrets.HZ_GITEE_TOKEN }}@gitee.com/thingspanel-go
          git push --force gitee main

    - name: Deploy and Check contents
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.DEV_HOST }}
        user: ${{ secrets.DEV_USER }}
        pass: ${{ secrets.DEV_PASS }}
        first_ssh: "ls -la /home/gowork/tp-tenant/thingspanel-go"
        last_ssh: |
          cd /home/gowork/tp-tenant/thingspanel-go
          git pull
          ./z-shell.sh
